spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 68468122-8955-45ee-a5b7-3d87972325b1
  datasource:
    url: jdbc:mysql://34.81.32.251:3306/test?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lzc123456
server:
  port: 9091
seata:
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default

